spring.application.name=document-flow
spring.datasource.url=jdbc:postgresql://localhost:5432/document_flow_db
spring.datasource.username=portfolio_user
spring.datasource.password=portfolio_password
spring.jpa.hibernate.ddl-auto=update