name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # GitHub podnosi bazę w tle
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: document_flow
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/document_flow
          SPRING_DATASOURCE_USERNAME: portfolio_user
          SPRING_DATASOURCE_PASSWORD: portfolio_password
          GEMINI_API_KEY: OFFLINE_MODE
        run: |
          cd backend
          chmod +x mvnw
          ./mvnw clean install
